questions = {
    ser = "siendo",
    estar = "estando",
    ir = "yendo",
    tener = "teniendo",
    hacer = "haciendo",
--[[
    ver = "viendo",
    poder = "pudiendo",
    dar = "dando",
    saber = "sabiendo",
    poner = "poniendo",
    pedir = "pidiendo",
    seguir = "siguiendo",
    servir = "sirviendo",
    elegir = "eligiendo",
    caer = "cayendo",
    oir = "oyendo",
    venir = "viniendo",
    traer = "trayendo",
    haber = "habiendo",
    salir = "saliendo",
    hablar = "hablando",
    mirar = "mirando",
    escuchar = "escuchando",
    ayudar = "ayudando",
    comer = "comiendo",
    aprender = "aprendiendo",
    deber = "debiendo",
    leer = "leyendo",
    vivir = "viviendo",
    permitir = "permitiendo",
    recibir = "recibiendo",
    abrir = "abriendo",
    alcanzar = "alcanzando",
    llegar = "llegando",
    buscar = "buscando",
    parecer = "pareciendo",
    conocer = "conociendo",
    querer = "queriendo",
    dirigir = "dirigiendo",
    construir = "construyendo",
    exigir = "exigiendo",
    jugar = "jugando",
    pensar = "pensando",
    empezar = "empezando",
    entender = "entendiendo",
    volver = "volviendo",
    doler = "doliendo",
    sentir = "sintiendo",
    morir = "muriendo",
    conseguir = "consiguiendo"
]]
}



