-- nouns 1
data = {
  ['este, esta']  = 'this',
  ['ese(o),esa']  = 'that',
  ['un']          = 'a',
  ['el, la']      = 'the',
  ['la cosa']     = 'thing',
  ['la parte']    = 'part',
  ['la vida']     = 'life',
  ['el día']      = 'day',
  ['el año']      = 'year',
  ['el hombre']   = 'man',
  ['el tiempo']   = 'time, weather',
  ['yo']          = 'i',
  ['mi']          = 'my',
  ['me']          = 'me',
  ['nos']         = 'us',
  ['él']          = 'he',
  ['ella']        = 'she',
  ['su']          = 'his, her',
  ['nuestro']     = 'our',
  ['primero']     = 'first',
}
